name: forge2d_benchmark
description: Simple benchmark for Forge2D

version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  forge2d:
    path: ../
  build_runner: ">=1.6.2 <2.0.0"
  build_web_compilers: ">=2.12.0 <3.0.0"
