name: forge2d_workspace
repository: https://github.com/flame-engine/forge2d
workspace:
  - packages/benchmark
  - packages/forge2d
  - packages/forge2d/example

environment:
  sdk: ^3.12.0

dev_dependencies:
  melos: ^8.1.0

melos:
  command:
    version:
      # Only allow versioning to happen on main branch.
      branch: main
      # Generates a link to a prefilled GitHub release creation page.
      releaseUrl: true
      includeCommitId: true
      linkToCommits: true

    bootstrap:
      environment:
        sdk: ^3.12.0
      dependencies:
        meta: ^1.16.0
        vector_math: ^2.1.4
        web: ^1.1.1
      dev_dependencies:
        dartdoc: ^8.3.4
        flame_lint: ^1.4.1
        test: ^1.26.3

  scripts:
    lint:all:
      steps:
        - melos analyze --fatal-infos
        - format
      description: Run all static analysis checks.

    format-check:
      run: melos exec dart format . --set-exit-if-changed
      description: Run `dart format` checks for all packages.

    dartdoc:
      exec: dart pub run dartdoc
      description: Run dartdoc checks for all packages.

    coverage:
      steps:
        - melos exec -- dart test --coverage
        - melos exec -- genhtml coverage/lcov.info --output-directory=coverage/
      packageFilters:
        dirExists: test
      description: Generate coverage for the selected package.

    benchmark:
      exec:
        command: dart web/bench2d.dart
      packageFilters:
        scope: forge2d_benchmark

    benchmark_serve:
      exec:
        command: dart pub global run webdev serve --release
      packageFilters:
        scope: forge2d_benchmark

    example:
      exec:
        command: dart pub global run webdev serve --release
      packageFilters:
        scope: forge2d_examples
