name: forge2d_benchmark
description: Simple benchmark for Forge2D
resolution: workspace

version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: ^3.12.0

dependencies:
  forge2d: ^0.15.0

dev_dependencies:
  flame_lint: ^1.4.1
