name: forge2d_examples
description: Samples showcasing Forge2D
version: 1.0.0+1
resolution: workspace

publish_to: 'none'

environment:
  sdk: ^3.12.0

dependencies:
  forge2d: ^0.14.2+1

dev_dependencies:
  flame_lint: ^1.4.1
